import React from 'react'
import { Button } from 'react-bootstrap'

export default function Deslomba3() {
  return (
      <div className='mt-5'>
          <h2 className='text-center container font-weight-bold'> Deskripsi Lomba Inovasi dan Teknologi</h2>
          <div className="container mt-5">
          <h3 className=' font-weight-bold'>Penjelasan Umum</h3>
          <p>Karya tulis yang dibuat untuk memecahkan suatu permasalahan dengan landasan  teori,  metode  ilmiah,  dan  contoh  metode  penulisan  karya  ilmiah. Biasanya Karya ilmiah berisikan data, fakta, dan solusi mengenai suatu masalah yang diangkat. Penulisan karya ilmiah dilakukan secara runtut dan sistematis</p>
              <h3 className=' font-weight-bold'>Penjelasan Lomba </h3>
             <h6>A.) KETENTUAN UMUM </h6>
             <p>&bull; TEMA "KONTRIBUSI TEKNOLOGI INFORMASI DALAM MENGHADAPI ERA SOCIETY 5.0</p>
        <p>&bull; MEMILIH SALAH SATU SUB TEMA BERIKUT : </p>
        <ul>
            <li>PERIKANAN</li>
            <li>KELAUTAN</li>
            <li>PERTANIAN</li>
            <li>KESEHATAN</li>
            <li>SOSIAL EKONOMI</li>
            <li>SMART CITY</li>
          </ul>
             <p>&bull; KARYA TULIS DAPAT MEMPRESENTASIKAN HASIL PENELTIAN, GAGASAN KONSEPTUAL, DAN APLIKASI TEORI YANG DIDUKUNG DATA DAN REFERENSI YANG AKURAT SESUAI DENGAN TEMA YANG TELAH DITENTUKAN</p>
             <p>&bull; KARYA TULIS BERSIFAT ORIGINAL DAN BUKAN PLAGIAT, BELUM PERNAH DIPUBLIKASIKAN SEBELUMNYA, DAN BELUM PERNAH MENJADI JUARA PADA EVENT SEBELUMNYA SERTA SEDANG TIDAK DIIKUTSERTAKAN DALAM AJANG LOMBA LAIN.</p>
             <p>&bull; KARYA TULIS BERSIFAT OBJEKTIF, TIDAK MENGUNDANG UNSUR SARA, DAN DIDUKUNG OLEH FAKTA YANG FAKTUAL.</p>
             <p>&bull; PENULISAN DILAKUKAN SECARA SISTEMATIS DAN LOGIS DENGAN PENGGUNAAN BAHASA INDONESIA YANG BAIK DAN BENAR (SESUAI EYD).</p>
             <p>&bull; SELURUH KARYA TULIS YANG DIKOMPETISIKAN DALAM KOMPETISI INI MENJADI MILIK PANITIA, SEHINGGA PANITIA MEMILIKI HAK UNTUK MEMPUBLIKASIKAN KARYA DENGAN TETAP MENCANTUMKAN NAMA PENULISNYA.</p>
             <h6>B.) KETENTUAN PENULISAN </h6>
             <ol>
              <li>BAGIAN AWAL</li>
              <ul>
                <li>Halaman Sampul (LAMPIRAN 1)</li>
                    <p>- JUDUL DIKETIK DENGAN HURUF KAPITAL, SESUAI DENGAN MASALAH YANG DITULIS, DAN TIDAK MEMBUKA PELUANG PENAFSIRAN GANDA.</p>
                    <p>- PENULISAN ANGGOTA TIM WAJIB MENGGUNAKAN NAMA LENGKAP YANG DISERTAI NIM</p>
                    <p>- NAMA PERGURUAN TINGGI, KOTA DAN TAHUN PENULISAN DITULIS DENGAN JELAS DAN BENAR</p>
                    <p>- SERTAKAN LOGO SEKOLAH DI BAGIAN TENGAH HALAMAN.</p>
                <li>LEMBAR PERNYATAAN KEASLIAN DAN PERNYATAAN BAHWA KARYA
                    TULIS BELUM PERNAH DILOMBAKAN DAN DIPUBLIKASIKAN DISERTAI MATERAI YANG DITANDATANGANI OLEH KETUA KELOMPOK (LAMPIRAN 2)</li>
                    <p>-  CONTOH LAMPIRAN 1 DAN 2 DAPAT DILIHAT PADA LINK DIBAWAH INI :</p>
                      <p><a href="https://drive.google.com/drive/folders/1w_LpN3fQx_ZlSsbNfo-2c00-k4ciohd-?usp=sharing">https://drive.google.com/drive/folders/1w_LpN3fQx_ZlSsbNfo-2c00-k4ciohd-?usp=sharing</a></p>
                    <p>- DAFTAR ISI DAN DAFTAR LAIN YANG DIPERLUKAN SEPERTI DAFTAR GAMBAR, DAFTAR TABEL, DAN DAFTAR     LAMPIRAN.</p>
                    <p>- ABSTRAK KARYA TULIS MAKSIMAL SATU HALAMAN YANG MENJELASKAN SECARA GARIS BESAR ISI DARI KESELURUHAN KARYA TULIS ILMIAH SESUAI DENGAN SUB TEMA YANG DIPILIH.</p>
                </ul>
              <li>BAGIAN ISI </li>
                  <ul>
                    <li>BAB I PENDAHULUAN</li>
                    <p>- LATAR BELAKANG PENULISAN </p>
                    <p>- RUMUSAN MASALAH </p>
                    <p>- TUJUAN DAN MANFAAT YANG INGIN DICAPAI </p>
                  <li>BAB II TINJAUAN PUSTAKA</li>
                  <p>- URAIAN YANG MENUNJUKKAN LANDASAN TEORI DAN KONSEP-KONSEP YANG RELEVAN DENGAN MASALAH YANG DIKAJI</p>
                  <p>- TERDAPAT KERANGKA BERPIKIR DAN PENELITIAN YANG RELEVAN</p>
                  <p>- KUTIPAN AKAN LEBIH BAIK BILA DIAMBIL DARI SUMBER PUSTAKA PRIMER SEPERTI JURNAL ILMIAH, BULETIN, BUKU, PROSIDING, ENSIKLOPEDIA, MAUPUN SUMBER INTERNET YANG VALID. NAMUN TIDAK DIPERBOLEHKAN MENGUTIP DARI BLOG PRIBADI ATAU WIKIPEDIA.</p>
                  </ul>
                  <ul>
                    <li>BAB III METODE PENULISAN</li>
                    <p>- METODE PENULISAN: MENGURAIKAN SECARA CERMAT CARA/ PROSEDUR PENGUMPULAN DATA, PENGOLAHAN DATA, SERTA ANALISIS-SINTESIS.</p>
                    <p>- METODE PENELITIAN: MENGURAIKAN SECARA CERMAT BAGAIMANA OBSERVASI DILAKUKAN, METODE YANG DILAKUKAN, ANALISIS YANG DILAKUKAN, DAN DESAIN ATAU GAMBARAN ALAT/ PRODUK/ PROTOTYPE ATAU PURWARUPA DARI KARYA TULIS. </p>
                  </ul>
                  <ul>
                    <li>BAB IV PEMBAHASAN (NON RESEARCH) / HASIL PEMBAHASAN (RESEARCH)</li>
                    <p>- NON  RESEARCH:  URAIAN  HASIL  KAJIAN,  TEMUAN,  IDE  PENGEMBANGAN  YANG  SESUAI DENGAN RUMUSAN MASALAH DAN TUJUAN DIDASARKAN PADA DATA ATAU INFORMASI, TINJAUAN PUSTAKA SERTA ANALISIS SWOT, BALANCED SCORECARD ATAU LAINNYA. </p>
                    <p>- RESEARCH: HASIL BERISI INFORMASI/DATA/ HASIL PENGUJIAN DATA DARI OBSERVASI ATAU PENELITIAN YANG DILAKUKAN. PEMABAHASAN BERISI TENTANG URAIAN, INTERPRETASI DATA DAN ANALISIS SWOT SWOT, BALANCED SCORECARD ATAU LAINNYA.</p>
                  </ul>
                  <ul>
                    <li>BAB V PENUTUP JUDUL SUB-BAB DARI BAGIAN PENUTUP</li>
                    <p>- SIMPULAN: KESIMPULAN HARUS KONSISTEN DENGAN ANALISIS PERMASALAHAN SERTA SESUAI DENGAN TUJUAN PENULISAN.</p>
                    <p>- SARAN: SARAN YANG DISAMPAIKAN HARUSLAH SPESIFIK SERTA SEJALAN DENGAN PERMASALAHAN YANG DIKAJI, KELEMAHAN/KEKURANGAN TULISAN, DAN BISA DITAMBAH DENGAN REKOMENDASI PENELITIAN SELANJUTNYA </p>
                  </ul>
                <li>BAGIAN AKHIR</li>
                <ul>
                  <li>	DAFTAR PUSTAKA DITULIS UNTUK MEMBERI INFORMASI SEHINGGA PEMBACA DAPAT DENGAN MUDAH MENEMUKAN SUMBER YANG DISEBUTKAN DENGAN MENGGUNAKAN SISTEM AMERICAN PSYCHOLOGICAL ASSOCIATION (APA) STYLE</li>
                  <li>LAMPIRAN: DAFTAR RIWAYAT HIDUP PENULIS BERISI: NAMA, TTL, ALAMAT LENGKAP, NOMOR TELEPON,  EMAIL,ASAL  PERGURUAN  TINGGI/  SEKOLAH,  RIWAYAT  PENDIDIKAN,  DAFTAR PUBLIKASI KARYA, DAN PRESTASI.</li>
                  <li>LAMPIRAN LAIN (JIKA DIPERLUKAN) , SEPERTI FOTO/ DOKUMENTASI, DATA DAN INFORMASI YANG MENDUKUNG ISI PEMBAHASAN KARYA TULIS</li>
                </ul>
             </ol>
             <h6>C.) PETUNJUK TEKNIK PENULISAN</h6>
             <p>&bull; NASKAH DITULIS MAKSIMAL 20 HALAMAN. JUMLAH HALAMAN YANG TIDAK SESUAI DENGAN KETENTUAN  TERSEBUT  DAPAT  MENGURANGI  PENILAIAN.  JUMLAH  INI  TIDAK  TERMASUK HALAMAN  JUDUL,   HALAMAN  PERNYATAAN  KEASLIAN,  KATA  PENGANTAR,  DAFTAR  ISI  DAN DAFTAR LAINNYA, SERTA LAMPIRAN-LAMPIRAN.</p>
             <p>&bull; BAHASA INDONESIA YANG DIGUNAKAN HARUS BAKU DENGAN TATA BAHASA DAN EJAAN SESUAI DENGAN PEDOMAN UMUM EJAAN BAHASA INDONESIA YANG DISEMPURNAKAN (PUEBI).</p>
             <p>&bull; PENULISAN JUDUL PADA HALAMAN SAMPUL DITULIS DENGAN JENIS UKURAN HURUF “TIMES NEW ROMAN 14” DAN DICETAK TEBAL</p>
             <p>&bull; PENULISAN HURUF NASKAH DIKETIK PADA KERTAS UKURAN A4 DENGAN 1,5 ANTAR SPASI DAN MENGGUNAKAN JENIS UKURAN HURUF “TIMES NEW ROMAN 12”.</p>
             <p>&bull; TATA LETAK BATAS PENGETIKAN: SAMPING KIRI 4 CM, SAMPING KANAN 3 CM, BATAS ATAS  4 CM ,BAWAH 3 CM.</p>
             <p>&bull; JARAK PENGETIKAN, BAB, SUB-BAB DENGAN RINCIAN :</p>
             <ul>
              <li>BAB DAN JUDUL BAB DIKETIK RATA TENGAH MENGGUNAKAN HURUF KAPITAL DAN DICETAK TEBAL</li>
              <li>JUDUL ANAK SUB-BAB DITULIS DARI SAMPING KIRI, HURUF PERTAMA SETIAP KATA DITULIS DENGAN HURUF KAPITAL</li>
             </ul>
             <p>&bull; PENGETIKAN KALIMAT PENGETIKAN KUTIPAN LANGSUNG YANG LEBIH DARI 3 BARIS DIKETIK 1 SPASI MENJOROK KEDALAM DAN SEMUANYA TANPA DIBERI TANDA PETIK.ATAS BAWAH 3 CM</p>
             <p>&bull; PENOMORAN HALAMAN</p>
             <ul>
              <li>NOMOR PADA BAGIAN AWAL MULAI DARI LEMBAR PERNYATAAN KEASLIAN HINGGA ABSTRAK DIGUNAKAN ANGKA ROMAWI KECIL (I,II,III, DAN SETERUSNYA), NOMOR HALAMAN DITULIS PADA BAGIAN KANAN BAWAH.</li>
              <li>BAGIAN INTI KARYA TULIS MULAI DARI PENDAHULUAN SAMPAI DENGAN BAGIAN PENUTUPAN MEMAKAI ANGKA (1, 2, 3, DAN SETERUSNYA). NOMOR HALAMAN DITULIS PADA BAGIAN KANAN BAWAH</li>
             </ul>
             <p>&bull; MENGUMPULKAN KARYA TULIS ILMIAH DENGAN FORMAT PDF DAN LINK YOUTUBE VIDEO KE LINK FORM YANG TERSEDIA SESUAI BATAS WAKTU PENGUMPULAN.</p>
             <p>&bull; LINK PENGUMPULAN : <a href="https://bit.ly/m/INVOFEST2022">https://bit.ly/m/INVOFEST2022</a></p>
             <p>&bull; PESERTA MENUNGGU PENGUMUMAN LOLOS TAHAP FINAL SESUAI WAKTU YANG SUDAH DITENTUKAN</p>
             <h6>D.) MELAKUKAN PRESENTASI DAN TANYA JAWAB </h6>
             <p>&bull; -	5 TIM YANG LOLOS TAHAP FINAL WAJIB MELAKUKAN PRESENTASI DAN SESI TANYA JAWAB SECARA ONLINE (LINK ZOOM)</p>
             <h6>E.) PENGUMUMAN JUARA 1, 2, 3 DAN PEMBERIAN E-SERTIFIKAT + UANG PEMBINAAN </h6>
             <br />
          <Button href='' className='btn btn-primary'>Guide book</Button>

        
          </div>
    </div>
  )
}
